// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using escuchify_api.Data;

#nullable disable

namespace escuchify_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ArtistaDiscos", b =>
                {
                    b.Property<int>("ArtistasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtistasId", "DiscosId");

                    b.HasIndex("DiscosId");

                    b.ToTable("ArtistaDiscos");
                });

            modelBuilder.Entity("escuchify_api.Core.Entities.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("escuchify_api.Core.Entities.Canciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscosID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscosID");

                    b.ToTable("Canciones");
                });

            modelBuilder.Entity("escuchify_api.Core.Entities.Discos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnioLanzamiento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelloDiscografico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tipodisco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Discos");
                });

            modelBuilder.Entity("ArtistaDiscos", b =>
                {
                    b.HasOne("escuchify_api.Core.Entities.Artista", null)
                        .WithMany()
                        .HasForeignKey("ArtistasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("escuchify_api.Core.Entities.Discos", null)
                        .WithMany()
                        .HasForeignKey("DiscosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("escuchify_api.Core.Entities.Canciones", b =>
                {
                    b.HasOne("escuchify_api.Core.Entities.Discos", "discos")
                        .WithMany("Canciones")
                        .HasForeignKey("DiscosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("discos");
                });

            modelBuilder.Entity("escuchify_api.Core.Entities.Discos", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
